### ISSUE TITLE
Latin samples?

### ISSUE THREAD

**Issue by frivoal** [w3c/type-samples#21]
On the one hand, we generally need more information on non-Latin typography than on Latin typography. On the other hand, even for Latin typography, there are plenty of traditional typographic features that are not yet appropriately supported on the web, and getting samples for that would be interesting. For instance, I have these lying around: https://www.dropbox.com/sh/tdneavxu2064kim/AACd4gMSIrhOIFeedjUDo91ra?dl=0, and I am sure that @dauwhe has plenty more.

Are we open to such things? If yes, do we try to set up some guideline to draw the line between stuff we are interested in and mundane stuff that is of no interest, or can we try and count on people being reasonable?

**Comment by r12a** [comment]
> Are we open to such things? 

Yes, as long as we don't flood the repo with Latin at the expense of the precious non-Latin stuff.  The latter is typically hard to come by unless you live in a country that uses that script, so one of the main reasons to set up the repo is to provide access to the typically more hidden stuff.

> If yes, do we try to set up some guideline to draw the line between stuff we are interested in and mundane stuff that is of no interest, or can we try and count on people being reasonable?

This echoes my own concern.  I don't think we can count on all people being reasonable, and i think we need some clear guidelines for the rest, so that they understand the objective here.  I brainstorm something here, but would welcome your builds/critique.

---

1. **Only add one image per issue.** Think of this as a repository for images that people can link to or reuse elsewhere, not a discussion list for script features. We are only using issues as containers because they are easy to work with, and so that people can make comments _about the image_ (eg. wrt quality, accuracy, etc.).
1. **Before uploading an image, check that there isn't already a similar one in the repo.**  (If you believe that your image is better than the one currently available, then it's ok to propose it as replacement, but we may remove one image if there are duplicates. If your images shows something that the other doesn't, it may also be ok to create a new issue for it.)
1. **An issue should illustrate a single feature.** If the image illustrates more than one feature, you can use it in more than one issue.
1. Ideally you would upload the image to the repo and then link to it in the issue you are creating.
1. **In the issue heading, list** 
  a. the language (not the script!) first, then 
  b. a succinct description of what the image shows.
1. **In the issue body,** please 
  a. add the image first, and all text below it
  a. identify the source of the image (also what type of source, to help us set labels), and 
  a. add a line to point out what the image illustrates (and if necessary, where on the image). **This should normally be no more than one sentence!**
1. Only submit images that qualify as **fair use**.

**Comment by r12a** [comment]
I'm re-examining this and playing around with alternate approaches, which may invalidate some of the guidelines above.  For example, i'm looking at adding a parseable format to the issue, and allowing a single issue/image to represent more than one feature. Stay tuned...

**Comment by r12a** [comment]
Stale.
