### ISSUE TITLE
jpan ja book ruby

### ISSUE THREAD

**Issue by himorin** [w3c/type-samples#92]
![image](https://user-images.githubusercontent.com/3918572/73122432-339a9800-3fc8-11ea-8739-62ea63352c1b.png)

---
tag: Ruby with stretched character narrower than 1/2 of main text
source: 「鋼の錬金術師 4 遠い空の下で」 (スクウェア・エニックス) https://magazine.jp.square-enix.com/top/comics/detail/9784757513150/
----

**Comment by r12a** [comment]
Closing this issue because:

1. There is no 'ruby' label (please read [the instructions](https://github.com/w3c/type-samples/blob/gh-pages/README.md#how-to-submit-an-image))
2. The index_label is missing from the descriptive text (please read [the instructions](https://github.com/w3c/type-samples/blob/gh-pages/README.md#how-to-submit-an-image))
3. The sample has very poor legibility.

If you successfully rectify these problems in this issue it will be reconsidered. Note that incorrect syntax will make the sample unavailable in the type samples index.
